### ISSUE TITLE
Schema: Add Filesize Field

### ISSUE THREAD

**Issue by ewlarson** [umass-gis/geoblacklight#10]
Add support for a filesize field like Cornell's cugir_filesize_s field:
https://cugir.library.cornell.edu/catalog/cugir-007297

This value is not automatically generated by GeoBlacklight, but would need to be calculated at metadata creation.

#### Open Question 
Is a string field the best place to capture this data? Support for multiple downloads exists in GeoBlacklight now, and it's likely each file would have a different size. Maybe the file label would be the best place for filesize information:
https://github.com/geoblacklight/geoblacklight/blob/main/spec/fixtures/solr_documents/multiple-downloads.json#L8

**Comment by rmseifried** [comment]
This is a new field in the [Aardvark schema ](https://docs.google.com/spreadsheets/d/1QQjUzRe8YdPGKK4h0GYoNPTow2zZ1f0KFA0zzZyHAsk/edit?usp=sharing)(glb_fileSize_s)
