### ISSUE TITLE
UMass Aardvark - Stringify dct_references_s values 

### ISSUE THREAD

**Issue by ewlarson** [umass-gis/geoblacklight#16]
Working with the new UMass Aardvark test fixtures and I'm seeing one "gotcha" here...

In GeoBlacklight, the dct_references_s value has to be a string and not an array or a hash/dictionary -- the value should be stringified and escaped JSON. What we currently have is valid and proper JSON, but Solr looks at this during index time and "thinks" it's a [nested child document](https://solr.apache.org/guide/8_0/indexing-nested-documents.html), rather than a simple string value to store.

This is valid JSON, but incorrect for GBL:
```json
{
 "dct_references_s": [
      {
        "http://schema.org/url":"https://credo.library.umass.edu/view/full/mufs190-1951-dpn1k100-i001",
        "http://schema.org/downloadUrl":"https://credo.library.umass.edu/media/mufs190-1951-dpn1k100-i001.reference.tif",
        "http://iiif.io/api/image":"https://credo.library.umass.edu/view/zoom/mufs190-1951-dpn1k100-i001"
        }
      ],
}
```

This would be correct:

```json
{
 "dct_references_s": "{\"http://schema.org/url\":\"https://credo.library.umass.edu/view/full/mufs190-1951-dpn1k100-i001\",\"http://schema.org/downloadUrl\":\"https://credo.library.umass.edu/media/mufs190-1951-dpn1k100-i001.reference.tif\",\"http://iiif.io/api/image\":\"https://credo.library.umass.edu/view/zoom/mufs190-1951-dpn1k100-i001\"}"
}
```

Here's an example file where I've fixed this field:
https://github.com/umass-gis/geoblacklight/blob/feature/aardvark-metadata/test/fixtures/files/umass_documents/mufs190-1951-dpn1k100-i001_geoblacklight.json

Let me know if this is confusing at all, or if you have any questions about generating the output necessary here.

**Comment by rmseifried** [comment]
Ah, thanks for catching this! 

I see that the example given in the wiki ([GeoBlacklight 1.0 Metadata Elements](https://github.com/geoblacklight/geoblacklight/wiki/GeoBlacklight-1.0-Metadata-Elements#references)) formats this field the correct way. I was thrown off by the examples in the (Multiple Download Links)[https://github.com/geoblacklight/geoblacklight/wiki/Multiple-Download-Links] examples. Are those formatted properly and I'm not seeing the difference?

**Comment by rmseifried** [comment]
Okay, those should all be updated: https://github.com/umass-gis/geoblacklight/tree/feature/aardvark-metadata/test_metadata

**Comment by ewlarson** [comment]
Closing via https://github.com/umass-gis/geoblacklight/commit/41da823a984e2844b780ecede2d8aaae7bfc729e
