### ISSUE TITLE
UMass Aardvark - dct_references_s iiif url

### ISSUE THREAD

**Issue by ewlarson** [umass-gis/geoblacklight#17]
Found another wrinkle in the UMass Aardvark metadata here. For an IIIF image, you'll want to link to the info.json file instead of the Credo IIIF page/viewer.

Incorrect
```
https://credo.library.umass.edu/view/zoom/mufs190-1951-dpn1k100-i001
```

Correct
```
https://credo.library.umass.edu/iiif/mufs190-1951-dpn1k100-i001-001.tif/info.json
```

**Comment by rmseifried** [comment]
Records updated!

**Comment by ewlarson** [comment]
Closing via https://github.com/umass-gis/geoblacklight/commit/af59a0b6ac5a613cd9fee79ba325ed2cd7b2caef
