### ISSUE TITLE
Metadata: http or https?

### ISSUE THREAD

**Issue by rmseifried** [umass-gis/geoblacklight#2]
Is there a preference for http or https in reference URLs? These appear in both the **identifier** and **references** fields.

**Comment by ewlarson** [comment]
It is mostly non-secure, just http, on the GBL wiki:
https://github.com/geoblacklight/geoblacklight/wiki/External-references

I think a lot of these standards just aren't on secure web servers.

**Comment by rmseifried** [comment]
Ah okay! I understand that the reference URIs are non-secure, so should the URLs for our repository's items follow suit? Would there be any potential hiccups if we use the https versions? Here's an example of the references for a test record:

`"references": "\"{\"http://schema.org/url\":\"https://credo.library.umass.edu/view/full/mufs190-1951-dpn1k100-i001\",\"http://schema.org/downloadUrl\":\"https://credo.library.umass.edu/media/mufs190-1951-dpn1k100-i001.reference.tif\",\"http://iiif.io/api/image\":\"https://credo.library.umass.edu/view/zoom/mufs190-1951-dpn1k100-i001\"}\"",
`

**Comment by ewlarson** [comment]
Yes! If you have secure resources, you should use the https protocol value to serve them. Secure is always best.
