### ISSUE TITLE
Copyright and License

### ISSUE THREAD

**Issue by ewlarson** [umass-gis/geoblacklight#5]
Review Copyright and License files.

**Comment by rmseifried** [comment]
[This](https://github.com/umass-gis/geoblacklight/blob/main/LICENSE) is the boilerplate Apache License Version 2.0 that is currently in our repo.

The recommended way to post an Apache license is to follow [this example](https://github.com/geoblacklight/geoblacklight/blob/main/LICENSE.txt) and replace the: “Copyright [yyyy] [name of copyright owner]” with “Copyright 2021 The Board of Trustees of the University of Massachusetts” (or whatever makes sense).

Waiting on response from Steve Bischof about how to proceed.

**Comment by rmseifried** [comment]
Followed Stanford's example, with abbreviated license file and no copyright file.
